#!/bin/bash

show_help() {
cat << EOF
Usage: ${0##*/} [-h] [-o] <program> <clingo options> <other programs> ...
Run hclingo with a declarative heuristic.

    -h              display this help and exit
    -o              offline heuristic
EOF
}

# process command line arguments
OFFLINE=0

OPTIND=1
while getopts ho opt; do
    case $opt in
        h)
            show_help
            exit 0
            ;;
        o)
            OFFLINE=1
            ;;
    esac
done
shift $(expr $OPTIND - 1 )

MFILE=$1
shift

# run hclingo
env MFILE=$MFILE OFFLINE=$OFFLINE hclingo dhclingo.lp $@
