#!/bin/bash

show_help() {
cat << EOF
Usage: ${0##*/} [-h] [-f heuristic] -- <clingo options> ...
Run hclingo with a declarative heuristic.

    -h              display this help and exit
    -f HEURISTIC    path to the declarative heuristic
EOF
}

# process command line arguments
HFILE=None

OPTIND=1
while getopts hf: opt; do
    case $opt in
        h)
            show_help
            exit 0
            ;;
        f)
            HFILE=$OPTARG
    esac
done
shift "$((OPTIND-1))"

# run hclingo
env HFILE=$HFILE hclingo dhclingo.lp $@
echo $@
