#!/bin/bash

show_help() {
cat << EOF
Usage: ${0##*/} [-h] [-o] [-c] <program> <clingo options> ...
Run hclingo with a declarative heuristic.

    -h              display this help and exit
    -o              offline heuristic
    -c              post conflict when no decision is made
    -r              restart heuristic on one-step backtracking
EOF
}

# process command line arguments
OFFLINE=0
CONFLICT=0
BTRACK=0

OPTIND=1
while getopts horc opt; do
    case $opt in
        h)
            show_help
            exit 0
            ;;
        o)
            OFFLINE=1
            ;;
        r)
            BTRACK=1
            ;;
        c)
            CONFLICT=1
            ;;
    esac
done
shift $(expr $OPTIND - 1 )

MFILE=$1
shift

# run hclingo
env MFILE=$MFILE OFFLINE=$OFFLINE BTRACK=$BTRACK CONFLICT=$CONFLICT hclingo dhclingo.lp $@
